# -----------------------------------------------------------------------------
# ROOT Terragrunt Configuration
# This is the root config inherited by all child configurations
# -----------------------------------------------------------------------------

# Generate provider configurations dynamically
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# Provider configuration is generated by Terragrunt
# See individual cloud folders for specific provider configs
EOF
}

# Remote state configuration (when ready to migrate from local)
# Uncomment and configure when you want remote state
#
# remote_state {
#   backend = "azurerm"
#   generate = {
#     path      = "backend.tf"
#     if_exists = "overwrite_terragrunt"
#   }
#   config = {
#     resource_group_name  = "rg-terraform-state"
#     storage_account_name = "stterraformstate"
#     container_name       = "tfstate"
#     key                  = "${path_relative_to_include()}/terraform.tfstate"
#   }
# }

# Common inputs for all environments
inputs = {
  project_name = "itb"

  # Common tags
  common_tags = {
    managed_by = "terragrunt"
    repository = "intelligent-trading-bot"
  }
}
